name: Build and release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: daviamsilva/arcade_mania
    steps:
      - uses: actions/checkout@v3

      - name: Build bin/arcade_mania.gba
        run: make release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Arcade Mania"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            bin/Arcade_Mania.gba
            LICENSE.txt